[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts',
    "solpp/=src/solpp/solpp-generated-contracts",
    "murky/=lib/murky/src",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
